import config

stringsMap = {
    "vi": {
        "text": "Văn bản",
        "image": "Ảnh",
        "gif": "Ảnh động GIF",
        "video": "Video",
        "attachment": "Tệp đính kèm",
        "textMedia": "Văn bản & Media ({mediaStr})",
        "mediaOnly": "Media ({mediaStr})",
        "msgDeletedOffline": "Tin nhắn bị xoá (Offline)",
        "msgDeleted": "Tin nhắn bị xoá",
        "author": "Người gửi",
        "channel": "Kênh",
        "sentTime": "Thời gian gửi",
        "replyTo": "Phản hồi đến tin nhắn ID",
        "noDbContent": "[Không tìm thấy nội dung trong DB]",
        "noTextContent": "[Không có nội dung chữ hoặc chứa Media]",
        "msgType": "Loại tin nhắn",
        "content": "Nội dung",
        "overLimit": "```\n[Vượt quá 1024 ký tự. Xem tệp đính kèm.]\n```",
        "noText": "```\n[Không có nội dung chữ]\n```",
        "sysWarning": "Cảnh báo hệ thống",
        "fileSizeError": "Tệp `{filename}` vượt quá dung lượng cho phép của máy chủ, bỏ qua tải lên.",
        "bulkReportHeader": "=== BÁO CÁO XOÁ TIN NHẮN HÀNG LOẠT - KÊNH {channelId} ===",
        "bulkReason": "Nguyên nhân xác định: {reason}",
        "bulkDetectTime": "Thời gian phát hiện: {time}",
        "bulkMsgAuthor": "[{time}] ID Tác giả: {authorId} | Tên: {name}",
        "bulkMsgId": "ID Tin nhắn: {id}",
        "bulkMsgContent": "Nội dung: {content}",
        "bulkTitle": "Phát hiện Xoá Tin nhắn Hàng loạt",
        "bulkDesc": "Ghi nhận tổng cộng **{count}** tin nhắn bị xóa đồng thời tại kênh <#{channelId}>.\nNguồn xác thực: **{reason}**.\nChi tiết toàn bộ tin nhắn được tổng hợp bên trong tệp văn bản.",
        "msgEdited": "Tin nhắn bị chỉnh sửa",
        "beforeEdit": "Trước khi sửa",
        "afterEdit": "Sau khi sửa",
        "empty": "[Trống]",
        "progressStr": "\rĐã nạp: {count} tin nhắn | Tốc độ: {speed:.2f} tin nhắn/giây",
        "scanCompleteStr": "Hoàn tất nạp {count} tin nhắn trong {time} giây",
        "ramUsageStr": "Mức sử dụng RAM: {ram:.2f} MB",
        "oldestMsgStr": "Thời gian tin nhắn cũ nhất đã quét: {date}",
        "botUsername": "Bot Username: {name}",
        "botId": "Bot ID: {id}",
        "reportSched": "Chế độ báo cáo định kỳ: {sched}",
        "sendReportLog": "Gửi báo cáo vào kênh log: {status}",
        "dbSuccess": "Trạng thái Database: Kết nối thành công",
        "dbFail": "Trạng thái Database: Kết nối thất bại",
        "dbSize": "Kích thước tệp Database: {size}",
        "monitoredChannels": "Số lượng kênh đang giám sát: {count}",
        "totalMembers": "Tổng số người trong máy chủ: {count}",
        "syncSlash": "Đã đồng bộ Slash Command thành công",
        "purgeReason": "Purge bởi Tác giả: {name} ({id})",
        "bulkUnknown": "Bulk Delete (Unknown)",
        "watchdogStagnation": "Watchdog detected task stagnation or crash: {name}! Safe reconstruction in progress...",
        "watchdogDeath": "Watchdog detected death in critical component: {name}! Resurrecting system loops...",
        "yes": "Có",
        "no": "Không",
        "botStarting": "MACB đang khởi động...",
        "shuttingDown": "Đang tiến hành tắt hệ thống an toàn...",
        "shutdownComplete": "Hệ thống đóng an toàn.",
        "statsTitle": "Trạng thái của MACB",
        "genStats": "Thống kê Chung",
        "uptimeStr": "{d} ngày, {h} giờ, {m} phút, {s} giây",
        "botInfo": "Thông tin Bot",
        "dbSection": "Cơ sở dữ liệu",
        "dbStatus": "Trạng thái",
        "dbFileSize": "Kích thước tệp",
        "loadedMsgs": "Tin nhắn đã nạp",
        "scanTimeField": "Thời gian nạp",
        "oldestMsgField": "Thời gian cũ nhất",
        "serverStats": "Thống kê Máy chủ",
        "monitoredChannelsField": "Kênh giám sát",
        "totalMembersField": "Tổng số người",
        "resourcesSection": "Tài nguyên",
        "ramUsageField": "Mức sử dụng RAM",
        "supportDiscord": "Discord Hỗ trợ",
        "periodicReportHourly": "Báo cáo định kỳ (hàng giờ)",
        "periodicReportDaily": "Báo cáo định kỳ (hàng ngày)",
        "publishTime": "Thời gian phát hành",
        "totalCurrentMessages": "Tổng số tin nhắn hiện tại",
        "newMessagesGenerated": "Tin nhắn mới phát sinh",
        "editedMessagesField": "Tin nhắn đã chỉnh sửa",
        "deletedMessagesField": "Tin nhắn đã xoá bỏ",
        "msgCountSuffix": "{count} tin nhắn",
        "loadingDbFirst": "Đang nạp dữ liệu tin nhắn vào database lần đầu... (quá trình này có thể mất vài giây hoặc vài phút).",
        "loadingDbSync": "Đang kiểm tra và đồng bộ dữ liệu tin nhắn với máy chủ... (quá trình này có thể mất vài giây hoặc vài phút).",
        "channelsProgressStr": "\rKênh: {completed}/{total} | Đã xử lý: {count} tin nhắn | Tốc độ: {speed:.2f} tin nhắn/giây",
        "scanCompleteFirstStr": "Hoàn tất nạp {count} tin nhắn vào database trong {time} giây",
        "scanCompleteSyncStr": "Hoàn tất đồng bộ {count} tin nhắn trong {time} giây",
        "oldestMsgStr": "Thời gian tin nhắn cũ nhất: {date}"
    },
    "en": {
        "text": "Text",
        "image": "Image",
        "gif": "Animated GIF",
        "video": "Video",
        "attachment": "Attachment",
        "textMedia": "Text & Media ({mediaStr})",
        "mediaOnly": "Media ({mediaStr})",
        "msgDeletedOffline": "Message Deleted (Offline)",
        "msgDeleted": "Message Deleted",
        "author": "Sender",
        "channel": "Channel",
        "sentTime": "Sent Time",
        "replyTo": "Replying to message ID",
        "noDbContent": "[Content not found in DB]",
        "noTextContent": "[No text content or contains Media]",
        "msgType": "Message Type",
        "content": "Content",
        "overLimit": "```\n[Exceeded 1024 characters. See attached file.]\n```",
        "noText": "```\n[No text content]\n```",
        "sysWarning": "System Warning",
        "fileSizeError": "File `{filename}` exceeds server payload limit, skipping upload.",
        "bulkReportHeader": "=== BULK DELETE REPORT - CHANNEL {channelId} ===",
        "bulkReason": "Identified Reason: {reason}",
        "bulkDetectTime": "Detection Time: {time}",
        "bulkMsgAuthor": "[{time}] Author ID: {authorId} | Name: {name}",
        "bulkMsgId": "Message ID: {id}",
        "bulkMsgContent": "Content: {content}",
        "bulkTitle": "Bulk Delete Detected",
        "bulkDesc": "Recorded a total of **{count}** messages deleted simultaneously in channel <#{channelId}>.\nVerification source: **{reason}**.\nFull details of messages are compiled inside the text file.",
        "msgEdited": "Message Edited",
        "beforeEdit": "Before Edit",
        "afterEdit": "After Edit",
        "empty": "[Empty]",
        "progressStr": "\rLoaded: {count} messages | Speed: {speed:.2f} messages/sec",
        "scanCompleteStr": "Completed loading {count} messages in {time} seconds",
        "ramUsageStr": "RAM Usage: {ram:.2f} MB",
        "oldestMsgStr": "Oldest scanned message time: {date}",
        "botUsername": "Bot Username: {name}",
        "botId": "Bot ID: {id}",
        "reportSched": "Periodic report mode: {sched}",
        "sendReportLog": "Send report to log channel: {status}",
        "dbSuccess": "Database Status: Connection Successful",
        "dbFail": "Database Status: Connection Failed",
        "dbSize": "Database File Size: {size}",
        "monitoredChannels": "Number of monitored channels: {count}",
        "totalMembers": "Total server members: {count}",
        "syncSlash": "Successfully synced Slash Commands",
        "purgeReason": "Purge by Author: {name} ({id})",
        "bulkUnknown": "Bulk Delete (Unknown)",
        "watchdogStagnation": "Watchdog detected task stagnation or crash: {name}! Safe reconstruction in progress...",
        "watchdogDeath": "Watchdog detected death in critical component: {name}! Resurrecting system loops...",
        "yes": "Yes",
        "no": "No",
        "botStarting": "MACB is starting...",
        "shuttingDown": "Safe shutdown in progress...",
        "shutdownComplete": "System closed safely.",
        "statsTitle": "MACB Status",
        "genStats": "General Statistics",
        "uptimeStr": "{d} days, {h} hours, {m} minutes, {s} seconds",
        "botInfo": "Bot Information",
        "dbSection": "Database",
        "dbStatus": "Status",
        "dbFileSize": "File Size",
        "loadedMsgs": "Loaded Messages",
        "scanTimeField": "Scan Time",
        "oldestMsgField": "Oldest Message",
        "serverStats": "Server Statistics",
        "monitoredChannelsField": "Monitored Channels",
        "totalMembersField": "Total Members",
        "resourcesSection": "Resources",
        "ramUsageField": "RAM Usage",
        "supportDiscord": "Support Discord",
        "periodicReportHourly": "Periodic Report (Hourly)",
        "periodicReportDaily": "Periodic Report (Daily)",
        "publishTime": "Publish Time",
        "totalCurrentMessages": "Total Current Messages",
        "newMessagesGenerated": "New Messages Generated",
        "editedMessagesField": "Edited Messages",
        "deletedMessagesField": "Deleted Messages",
        "msgCountSuffix": "{count} messages",
        "loadingDbFirst": "Populating message data into database for the first time... (this process may take a few seconds or minutes).",
        "loadingDbSync": "Checking and synchronizing message data with the server... (this process may take a few seconds or minutes).",
        "channelsProgressStr": "\rChannels: {completed}/{total} | Processed: {count} messages | Speed: {speed:.2f} messages/sec",
        "scanCompleteFirstStr": "Successfully loaded {count} messages into the database in {time} seconds",
        "scanCompleteSyncStr": "Successfully synchronized {count} messages in {time} seconds",
        "oldestMsgStr": "Oldest message time: {date}"
    }
}

def getLocaleString(key, **kwargs):
    lang = getattr(config, "botLang", "vi")
    targetLang = lang if lang in stringsMap else "vi"
    return stringsMap[targetLang].get(key, "").format(**kwargs)